package(
    default_visibility = ["//third_party/tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "jni_utils",
    srcs = [
        "jni_utils.cc",
    ],
    hdrs = [
        "jni_utils.h",
    ],
    deps = [
        "//third_party/absl/strings",
        "//third_party/tensorflow/lite/java/jni",
    ],
)

cc_library(
    name = "common_utils",
    srcs = [
        "common_utils.cc",
    ],
    hdrs = [
        "common_utils.h",
    ],
)
