package(
    default_visibility = ["//third_party/tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "common",
    srcs = [
        "common.cc",
    ],
    hdrs = ["common.h"],
    deps = [
        "//third_party/absl/status",
        "//third_party/absl/strings",
        "//third_party/absl/strings:cord",
    ],
)
